import { defineConfig } from "tsup";

/**
 * The release tools as one self-contained ES module for the composite actions
 * (actions/lib/release-tools.mjs). It is committed, so an action runs without
 * an install step; CI rebuilds it and fails when the committed file differs.
 * Bundled third-party code: zod (MIT), yaml (ISC); see THIRD_PARTY_NOTICES.
 */
export default defineConfig({
  entry: { "release-tools": "src/bin.ts" },
  outDir: "../../actions/lib",
  outExtension: () => ({ js: ".mjs" }),
  format: ["esm"],
  target: "node22",
  platform: "node",
  bundle: true,
  noExternal: [/.*/],
  splitting: false,
  treeshake: true,
  minify: false,
  sourcemap: false,
  clean: false,
  dts: false,
  removeNodeProtocol: false,
  // yaml resolves to its CommonJS build on Node; give it a require().
  banner: {
    js: [
      "// Generated by `pnpm --filter @cicd-updater/release-tools build`; do not edit.",
      "// cicd-updater release tools. Copyright IT Systeme Flores UG (haftungsbeschränkt), Apache-2.0.",
      "// Bundles zod (MIT) and yaml (ISC); see THIRD_PARTY_NOTICES in the repository.",
      'import { createRequire as __cicdCreateRequire } from "node:module";',
      "const require = __cicdCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});
