/**
 * Writes the generated contract files: `schemas/*.schema.json`,
 * `openapi/updater-api.v1.yaml` and the generated reference section of
 * `docs/configuration.md`. With `--check` nothing is written; the script fails
 * when a committed file differs from what would be generated (CI drift check).
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemas, openApiDocument } from "@cicd-updater/protocol";
import { stringify } from "yaml";
import { renderConfigReference } from "./config-reference.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const drift: string[] = [];

async function emit(relative: string, content: string): Promise<void> {
  const file = join(root, relative);
  let current: string | null = null;
  try {
    current = await readFile(file, "utf8");
  } catch {
    current = null;
  }
  if (current === content) {
    return;
  }
  if (check) {
    drift.push(relative);
    return;
  }
  await writeFile(file, content);
  console.log(`wrote ${relative}`);
}

for (const [name, schema] of Object.entries(jsonSchemas())) {
  await emit(join("schemas", name), `${JSON.stringify(schema, null, 2)}\n`);
}

const header = "# Generated by scripts/generate.ts from packages/protocol. Do not edit by hand.\n";
await emit(
  join("openapi", "updater-api.v1.yaml"),
  header + stringify(openApiDocument(), { lineWidth: 0, aliasDuplicateObjects: false }),
);

const BEGIN = "<!-- BEGIN GENERATED: configuration reference -->";
const END = "<!-- END GENERATED: configuration reference -->";
const docPath = join("docs", "configuration.md");
const doc = await readFile(join(root, docPath), "utf8").catch(() => null);
if (doc?.includes(BEGIN) && doc.includes(END)) {
  const before = doc.slice(0, doc.indexOf(BEGIN) + BEGIN.length);
  const after = doc.slice(doc.indexOf(END));
  await emit(docPath, `${before}\n\n${renderConfigReference()}\n${after}`);
} else if (check) {
  drift.push(`${docPath} (markers missing)`);
}

if (drift.length > 0) {
  console.error(`Generated files are out of date: ${drift.join(", ")}. Run pnpm generate.`);
  process.exit(1);
}
if (check) {
  console.log("Generated files are up to date.");
}
