/**
 * Writes THIRD_PARTY_NOTICES: the licences of every npm package that reaches a
 * shipped artefact (the sidecar bundle, the action bundle, the SDK's dependency)
 * with their full licence texts, and the components of the container image.
 * Fails when a package has a licence outside the permissive allowlist.
 * With `--check` nothing is written; the script fails on drift (CI).
 *
 *   pnpm notices [--check]
 */
import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = join(import.meta.dirname, "..");
const check = process.argv.includes("--check");
const ALLOWED = new Set(["MIT", "ISC", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "0BSD"]);
// The shipped packages; their production dependencies are collected transitively.
const SHIPPED = ["packages/sidecar", "packages/release-tools", "packages/sdk"];

interface Manifest {
  name: string;
  version: string;
  license?: string;
  repository?: string | { url?: string };
  dependencies?: Record<string, string>;
}

const found = new Map<string, { manifest: Manifest; dir: string }>();
const problems: string[] = [];

/** node_modules lookup from a directory upwards (exports maps may hide package.json). */
function packageManifest(fromDir: string, name: string): string | null {
  let dir = fromDir;
  for (;;) {
    const candidate = join(dir, "node_modules", name, "package.json");
    if (existsSync(candidate)) {
      return realpathSync(candidate);
    }
    const parent = dirname(dir);
    if (parent === dir) {
      return null;
    }
    dir = parent;
  }
}

function collect(fromDir: string, name: string): void {
  if (name.startsWith("@cicd-updater/")) {
    const dir = join(root, "packages", name.slice("@cicd-updater/".length));
    const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as Manifest;
    for (const dependency of Object.keys(manifest.dependencies ?? {})) {
      collect(dir, dependency);
    }
    return;
  }
  const manifestPath = packageManifest(fromDir, name);
  if (!manifestPath) {
    problems.push(`${name} (needed by ${fromDir}) is not installed`);
    return;
  }
  const dir = dirname(manifestPath);
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest;
  const key = `${manifest.name}@${manifest.version}`;
  if (found.has(key)) {
    return;
  }
  found.set(key, { manifest, dir });
  for (const dependency of Object.keys(manifest.dependencies ?? {})) {
    collect(dir, dependency);
  }
}

for (const pkg of SHIPPED) {
  const dir = join(root, pkg);
  const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as Manifest;
  for (const dependency of Object.keys(manifest.dependencies ?? {})) {
    collect(dir, dependency);
  }
}

function licenceText(dir: string): string | null {
  for (const name of ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "license", "COPYING"]) {
    try {
      return readFileSync(join(dir, name), "utf8").trim();
    } catch {
      // next candidate
    }
  }
  return null;
}

const sections: string[] = [];
for (const [key, { manifest, dir }] of [...found.entries()].sort(([a], [b]) =>
  a.localeCompare(b),
)) {
  const licence = manifest.license ?? "UNKNOWN";
  if (!ALLOWED.has(licence)) {
    problems.push(`${key}: licence ${licence} is not in the allowlist`);
  }
  const text = licenceText(dir);
  if (!text) {
    problems.push(`${key}: no licence file`);
  }
  const repository =
    typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url;
  sections.push(
    [
      `${manifest.name} ${manifest.version}`,
      `Licence: ${licence}`,
      ...(repository ? [`Source: ${repository.replace(/^git\+/, "")}`] : []),
      "",
      text ?? "",
    ].join("\n"),
  );
}

const header = `THIRD-PARTY NOTICES

cicd-updater is Copyright IT Systeme Flores UG (haftungsbeschränkt) and licensed
under the Apache License 2.0 (LICENSE). It includes or ships with the third-party
software below, under the licences named. This file is generated by
scripts/third-party-notices.ts; do not edit it by hand.

PART 1: npm packages

These packages are bundled into the sidecar (/opt/cicd-updater/cicd-updater.mjs in
the image) and into the release tools of the actions (actions/lib/release-tools.mjs).
The SDK (@restow-backup/cicd-updater) depends on zod and bundles none of them.
`;

const image = `PART 2: components of the container image

The image ghcr.io/restow-backup/cicd-updater contains, besides the bundle above,
these programs, unmodified, from their official distributions (docker/Dockerfile
pins each by digest or takes it from Alpine Linux's signed packages):

- Node.js 24 (MIT, plus the licences of its bundled components listed in
  https://github.com/nodejs/node/blob/main/LICENSE), from the official
  node:24-alpine image.
- Alpine Linux base system (among others musl, MIT, and BusyBox, GPL-2.0, whose
  tar the volume backup uses), https://alpinelinux.org; package sources at
  https://gitlab.alpinelinux.org/alpine/aports.
- Docker CLI (Apache-2.0), https://github.com/docker/cli
- Docker Buildx (Apache-2.0), https://github.com/docker/buildx
- Docker Compose (Apache-2.0), https://github.com/docker/compose
  (the three above from the official docker:cli image)
- cosign (Apache-2.0), https://github.com/sigstore/cosign
  (from the official ghcr.io/sigstore/cosign/cosign image)
- age (BSD-3-Clause), https://github.com/FiloSottile/age (Alpine package)
- tini (MIT), https://github.com/krallin/tini (Alpine package)
- ca-certificates (MPL-2.0 for the certificate data), Alpine package

The Apache License 2.0 text is in LICENSE. The licence texts of the Alpine
packages are part of their sources; the BusyBox (GPL-2.0) sources are available
from Alpine Linux as linked above. cicd-updater runs these programs as separate
processes; it does not link them.
`;

const content = `${header}\n${"=".repeat(78)}\n\n${sections.join(`\n\n${"-".repeat(78)}\n\n`)}\n\n${"=".repeat(78)}\n\n${image}`;

if (problems.length > 0) {
  for (const problem of problems) {
    console.error(problem);
  }
  process.exit(1);
}
const target = join(root, "THIRD_PARTY_NOTICES");
let current: string | null = null;
try {
  current = readFileSync(target, "utf8");
} catch {
  current = null;
}
if (check) {
  if (current !== content) {
    console.error("THIRD_PARTY_NOTICES is out of date: run pnpm notices");
    process.exit(1);
  }
  console.log(`THIRD_PARTY_NOTICES is up to date (${found.size} packages).`);
} else {
  writeFileSync(target, content);
  console.log(`wrote THIRD_PARTY_NOTICES (${found.size} packages)`);
}
